import {BLOCKS, VARIABLES, calculate, weightLossPercent, actionsForPriority, PERIODICITY, REASSESS_WHEN, MIN_OVERRIDE_LENGTH} from './clinical.js';
import {listCases,saveCase,getCase,deleteCase,duplicateCase,exportStructured,importStructured,exportCsv,saveActiveCase,getActiveCase,clearActiveCase} from './storage.js';
import {extractClinicalText} from './extractor.js';
import {initialAssessmentState,mergeExtraction,markManual,confirmVariable,effectiveAnswers,canFinalize,CRITICAL_VARIABLES} from './assessment-state.js';

const $=s=>document.querySelector(s), form=$('#assessmentForm'); let currentId=null,appState=initialAssessmentState(),applying=false;
const boolField=(name)=>`<fieldset><legend>${name}</legend><label><input type="radio" name="${name}" value="true"> Sí</label><label><input type="radio" name="${name}" value="false"> No</label></fieldset>`;
const number=(name,min=0,max='',step=1,unit='')=>`<label>${unit?`Valor (${unit})`:'Valor'}<input type="number" name="${name}" min="${min}" ${max!==''?`max="${max}"`:''} step="${step}"></label>`;
function controls(v){const map={
 age:number('age',0,120),weightLoss:`<div class="grid">${number('weightPrevious',0.1,'',0.1,'kg hace 3 meses')}${number('weightCurrent',0.1,'',0.1,'kg actual')}</div>${boolField('weightLossInvoluntary')}<output id="weightOutput">Pérdida calculada: —</output>`,pregnancy:boolField('pregnancy'),unhealthyHabits:boolField('unhealthyHabits'),communicationBarriers:boolField('communicationBarriers'),psychiatricHistory:boolField('psychiatricHistory'),
 psychologicalDistress:`<label>Método<select name="distressMethod"><option value="">Pendiente</option><option value="none">Sin sospecha / no procede</option><option value="hads">HADS</option><option value="eva">EVA Distress NCCN</option></select></label><div class="grid">${number('hadsTotal',0,42,1,'HADS total')}${number('hadsAnxiety',0,21,1,'HADS ansiedad')}${number('hadsDepression',0,21,1,'HADS depresión')}${number('distressEva',0,10,1,'EVA Distress')}</div><p class="rule">Complete solo un sistema. Si constan ambos, prevalece HADS.</p>`,
 pfeiffer:`${number('pfeifferErrors',0,10,1,'errores')}${boolField('literate')}`,ecog:`<label>ECOG<select name="ecog"><option value="">Pendiente</option>${[0,1,2,3,4].map(x=>`<option>${x}</option>`).join('')}</select></label>`,socialSupport:boolField('socialSupport'),comorbidities:number('chronicDiseases',0,30,1),doseAdjustment:boolField('doseAdjustment'),pain:`${number('painEva',0,10,1,'EVA dolor')}${boolField('poorPainControl')}`,acuteCare:boolField('acuteCare'),dysphagia:boolField('dysphagia'),treatmentSituation:`<label>Situación<select name="treatmentSituation"><option value="">Pendiente</option><option value="neither">Ninguna</option><option value="firstOrChange">Primer ciclo o cambio</option><option value="thirdOrLater">Tercera línea o posterior</option></select></label>`,polypharmacy:number('homeMedicines',0,50,1),routeChange:boolField('routeChange'),regimenModification:boolField('regimenModification'),highRiskMedication:boolField('highRiskMedication'),specialStorage:boolField('specialStorage'),complexRegimen:`<label>Situación<select name="complexRegimen"><option value="">Pendiente</option><option value="none">Ninguna</option><option value="one">Un medicamento oral, pauta discontinua</option><option value="multiple">Dos o más, pautas discontinuas/diferentes</option></select></label>`,
 interactions:['interactionCam','interactionPk','interactionC','interactionDX'].map(boolField).join(''),toxicity:number('toxicityGrade',0,5,1,'grado CTCAE/CTC'),adherence:`${number('dispensingPercent',0,100,0.1,'% dispensación')}${boolField('moriskyIncorrect')}`,specialTreatment:['clinicalTrial','specialUse','recentlyMarketed'].map(boolField).join('')};return map[v.id];}
$('#blocks').innerHTML=BLOCKS.map(b=>`<section class="block"><div class="block-title"><span>${b.id}</span><div><h2>${b.title}</h2><small id="subtotal${b.id}">0 puntos</small></div></div>${VARIABLES.filter(v=>v.block===b.id).map(v=>`<article class="card variable" data-id="${v.id}"><div class="variable-head"><h3>${v.label}</h3><div><span class="origin pending">Pendiente</span> <span class="points">0 / ${v.max}</span></div></div><p>${v.help}</p>${controls(v)}<div class="trace-actions" hidden><button type="button" class="evidence secondary">Ver evidencia</button><button type="button" class="confirm-extraction">Confirmar dato</button></div><p class="evidence-text" hidden></p></article>`).join('')}</section>`).join('');

function answers(){const a={};new FormData(form).forEach((v,k)=>{a[k]=v==='true'?true:v==='false'?false:v;});return a;}
function metadata(){const a=answers();return {hospital:a.hospital,pharmacist:a.pharmacist,patientId:a.patientId,date:a.date,patientType:a.patientType};}
function override(){if(!$('#overrideEnabled').checked)return null;return {priority:Number($('#overridePriority').value),justification:$('#overrideJustification').value.trim(),modifiedAt:new Date().toISOString()};}
function refresh(){appState={...appState,currentId,metadata:metadata(),answers:answers(),override:override()};const a=effectiveAnswers(appState),r=calculate(a,override());$('#liveScore').textContent=r.score;$('#livePriority').textContent=`Prioridad ${r.finalPriority}`;$('#livePriority').className=`priority p${r.finalPriority}`;const total=[...new Set(VARIABLES.flatMap(v=>v.required))].length,done=total-r.pending.length,pct=Math.round(done/total*100);$('#progressBar').style.width=`${pct}%`;$('#progressText').textContent=`${pct}%`;$('#pendingText').textContent=r.pending.length?`${r.pending.length} campos clínicos pendientes`:'Variables clínicas completas';BLOCKS.forEach(b=>$('#subtotal'+b.id).textContent=`${r.subtotals[b.id]} puntos`);VARIABLES.forEach(v=>{const card=form.querySelector(`[data-id="${v.id}"]`),trace=appState.extraction?.[v.id],badge=card.querySelector('.origin'),traceActions=card.querySelector('.trace-actions');card.querySelector('.points').textContent=`${v.score(a)} / ${v.max}`;const review=trace&&(trace.confidenceStatus==='suggested'||CRITICAL_VARIABLES.has(v.id)&&trace.confidenceStatus==='confirmed')&&!trace.reviewed;badge.textContent=trace?.confidenceStatus==='manual'?'Manual':review?'Revisar':trace?.confidenceStatus==='confirmed'||trace?.reviewed?'Extraído':'Pendiente';badge.className=`origin ${badge.textContent.toLowerCase().replace('í','i')}`;traceActions.hidden=!trace||trace.confidenceStatus==='not_found'||trace.confidenceStatus==='manual';card.classList.toggle('needs-review',review);});const p=weightLossPercent(a.weightPrevious,a.weightCurrent);$('#weightOutput').textContent=`Pérdida calculada: ${p===null?'—':p.toFixed(2)+' %'}`;const meaningful=currentId||Object.keys(appState.answers||{}).some(k=>!['date'].includes(k))||Object.keys(appState.extraction||{}).length||appState.metadata.hospital||appState.metadata.pharmacist||appState.metadata.patientId||appState.metadata.patientType;if(meaningful)saveActiveCase(appState);else clearActiveCase();return r;}
form.addEventListener('input',e=>{if(!applying&&e.target.name)appState=markManual(appState,e.target.name,e.target.type==='radio'?e.target.value==='true':e.target.value);refresh();});$('#overrideEnabled').addEventListener('change',e=>{$('#overrideFields').hidden=!e.target.checked;refresh();});
function record(status){const o=override();if(o&&o.justification.length<MIN_OVERRIDE_LENGTH)throw new Error(`La justificación debe tener al menos ${MIN_OVERRIDE_LENGTH} caracteres.`);const r=calculate(answers(),o);const extraction=Object.fromEntries(Object.entries(appState.extraction||{}).map(([k,v])=>[k,{...v,evidence:undefined}]));return {id:currentId,status,metadata:metadata(),answers:answers(),extraction,result:r,actions:actionsForPriority(r.finalPriority)};}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500);}
$('#saveDraft').onclick=()=>{try{const saved=saveCase(record('draft'));currentId=saved.id;toast('Borrador guardado localmente.');}catch(e){toast(e.message);}};
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;try{const validation=canFinalize({...appState,answers:answers()});if(validation.extractionPending.length){toast(`No puede finalizar la estratificación. Hay ${validation.extractionPending.length} variables extraídas automáticamente pendientes de revisión.`);form.querySelector('.needs-review')?.scrollIntoView({behavior:'smooth',block:'center'});return;}if(validation.clinicalPending.length){toast(`No puede finalizar: quedan ${validation.clinicalPending.length} campos clínicos pendientes.`);return;}let rec=record('completed');rec=saveCase(rec);currentId=rec.id;$('#clinicalText').value='';appState={...appState,status:'completed',extraction:Object.fromEntries(Object.entries(appState.extraction||{}).map(([k,v])=>[k,{...v,evidence:''}]))};renderResult(rec);refresh();toast('Estratificación finalizada y guardada.');}catch(err){toast(err.message);}});
function renderResult(rec){const r=rec.result,a=rec.actions;$('#result').innerHTML=`<article class="result-card p${r.finalPriority}"><span>Resultado final</span><h2>PRIORIDAD ${r.finalPriority}</h2><p>${r.finalPriority===1?'Alta':r.finalPriority===2?'Necesidad intermedia de':'Necesidad estándar de'} seguimiento farmacéutico.</p><div class="result-grid"><div><small>Puntuación</small><strong>${r.score} / 96</strong></div><div><small>Por puntuación</small><strong>P${r.calculatedPriority}</strong></div><div><small>Automática</small><strong>${r.automaticPriority?'Sí: '+r.automaticReasons.join(', '):'No'}</strong></div><div><small>Prioridad final</small><strong>P${r.finalPriority}</strong></div></div>${r.override?`<p><strong>Modificación clínica (${new Date(r.override.modifiedAt).toLocaleString('es')}):</strong> ${r.override.justification}</p>`:''}</article><article class="card"><h2>Resumen por bloques</h2><div class="chips">${BLOCKS.map(b=>`<span>B${b.id}: ${r.subtotals[b.id]}</span>`).join('')}</div><h3>Variables positivas</h3><ul>${r.positiveVariables.map(v=>`<li>${v.label}: <strong>${v.points} puntos</strong></li>`).join('')||'<li>Ninguna</li>'}</ul>${r.pending.length?`<p class="warning">Pendientes: ${r.pending.join(', ')}</p>`:''}</article><article class="card"><h2>Actuaciones acumulativas recomendadas</h2>${[['follow','Seguimiento farmacoterapéutico'],['education','Formación, educación y seguimiento del paciente'],['coordination','Coordinación con el equipo asistencial']].map(([k,t])=>`<h3>${t}</h3><ul>${a[k].map(x=>`<li>${x}</li>`).join('')}</ul>`).join('')}<h3>Reestratificación</h3><p><strong>${PERIODICITY[r.finalPriority]}</strong></p><ul>${REASSESS_WHEN.map(x=>`<li>${x}</li>`).join('')}</ul></article><div class="actions"><button data-export="json">Exportar JSON</button><button data-export="csv" class="secondary">Exportar CSV</button><button onclick="window.print()" class="secondary">Imprimir / PDF</button></div>`;$('#result').scrollIntoView({behavior:'smooth'});$('#result').querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>download(b.dataset.export==='json'?exportStructured(rec):exportCsv(rec),`cmo-${rec.metadata.patientId||rec.id}.${b.dataset.export}`,b.dataset.export==='json'?'application/json':'text/csv'));}
function download(data,name,type){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
function fill(rec){applying=true;form.reset();currentId=rec.id||null;appState={...initialAssessmentState(),...rec,currentId,extraction:rec.extraction||{},manualFields:rec.manualFields||[]};Object.entries({...rec.metadata,...rec.answers}).forEach(([k,v])=>{const els=form.querySelectorAll(`[name="${CSS.escape(k)}"]`);els.forEach(el=>el.type==='radio'?el.checked=String(v)===el.value:el.value=v??'');});const o=rec.result?.override;$('#overrideEnabled').checked=!!o;$('#overrideFields').hidden=!o;if(o){$('#overridePriority').value=o.priority;$('#overrideJustification').value=o.justification;}applying=false;refresh();if(rec.status==='completed')renderResult(rec);}
function renderCases(){$('#caseList').innerHTML=listCases().map(c=>`<article class="saved"><div><strong>${c.metadata?.patientId||'Sin identificador'}</strong><small>${c.metadata?.date||''} · ${c.status==='completed'?'Finalizado':'Borrador'} · P${c.result?.finalPriority}</small></div><div><button data-load="${c.id}">Abrir</button><button data-copy="${c.id}" class="secondary">Duplicar</button><button data-delete="${c.id}" class="danger">Eliminar</button></div></article>`).join('')||'<p>No hay casos guardados.</p>';}
$('#casesButton').onclick=()=>{renderCases();$('#casesDialog').showModal();};$('#closeCases').onclick=()=>$('#casesDialog').close();$('#caseList').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.load){fill(getCase(b.dataset.load));$('#casesDialog').close();}if(b.dataset.copy){duplicateCase(b.dataset.copy);renderCases();}if(b.dataset.delete&&confirm('¿Eliminar este caso local?')){deleteCase(b.dataset.delete);renderCases();}};
$('#importFile').onchange=async e=>{try{const rec=importStructured(await e.target.files[0].text());delete rec.id;const saved=saveCase(rec);fill(saved);$('#casesDialog').close();toast('Caso importado.');}catch(err){toast(err.message);}};
form.date.value=new Date().toISOString().slice(0,10);refresh();

function applyAnswers(a){applying=true;Object.entries(a).forEach(([k,v])=>form.querySelectorAll(`[name="${CSS.escape(k)}"]`).forEach(el=>el.type==='radio'?el.checked=String(v)===el.value:el.value=v??''));applying=false;refresh();}
$('#analyzeClinical').onclick=()=>{const text=$('#clinicalText').value.trim();if(!text){toast('Pegue primero texto clínico para analizar.');return;}const preserveManual=!appState.manualFields?.length||confirm('Existen valores modificados manualmente. ¿Desea conservarlos?\n\nAceptar: conservar cambios manuales (recomendado).\nCancelar: sobrescribirlos con la nueva extracción.');$('#analyzeClinical').disabled=true;$('#analyzeClinical').textContent='Analizando información…';setTimeout(()=>{const extraction=extractClinicalText(text);appState=mergeExtraction(appState,extraction,{preserveManual});if(!preserveManual)appState.manualFields=[];applyAnswers(appState.answers);const s=extraction.summary;$('#extractionSummary').hidden=false;$('#extractionSummary').innerHTML=`<h3>Información identificada</h3><p>Se han identificado datos para <strong>${s.confirmed+s.suggested} de ${s.confirmed+s.suggested+s.not_found}</strong> variables.</p><div class="summary-counts"><span>Confirmadas: <b>${s.confirmed}</b></span><span>Requieren revisión: <b>${s.suggested}</b></span><span>No encontradas: <b>${s.not_found}</b></span></div><button type="button" id="continueReview">Continuar y revisar variables</button>`;$('#continueReview').onclick=()=>$('#assessmentStart').scrollIntoView({behavior:'smooth'});$('#analyzeClinical').disabled=false;$('#analyzeClinical').textContent='Reanalizar historia clínica';},20);};
$('#blocks').addEventListener('click',e=>{const card=e.target.closest('.variable');if(!card)return;const id=card.dataset.id,trace=appState.extraction?.[id];if(e.target.classList.contains('evidence')){const p=card.querySelector('.evidence-text');p.hidden=!p.hidden;p.textContent=trace?.evidence?`Evidencia: “${trace.evidence}” · ${trace.reason}`:'La evidencia no se conserva en este caso.';}if(e.target.classList.contains('confirm-extraction')){appState=confirmVariable(appState,id);refresh();toast('Dato revisado y confirmado.');}});
$('#newAssessment').onclick=()=>$('#resetDialog').showModal();$('#cancelReset').onclick=()=>$('#resetDialog').close();$('#confirmReset').onclick=()=>{clearActiveCase();appState=initialAssessmentState();currentId=null;applying=true;form.reset();form.date.value=appState.metadata.date;$('#clinicalText').value='';$('#extractionSummary').hidden=true;$('#result').innerHTML='';$('#overrideFields').hidden=true;applying=false;$('#resetDialog').close();refresh();form.hospital.focus();toast('Nueva estratificación preparada. Los casos guardados se conservan.');};
const active=getActiveCase();if(active)fill(active);
