import {VARIABLES} from './clinical.js';

export const CRITICAL_VARIABLES=new Set(['age','pregnancy','socialSupport','pfeiffer','ecog','doseAdjustment','regimenModification','treatmentSituation','interactions','toxicity','adherence']);
export function initialAssessmentState(today=new Date().toISOString().slice(0,10)){return {currentId:null,metadata:{hospital:'',pharmacist:'',patientId:'',date:today,patientType:''},answers:{},extraction:{},manualFields:[],status:'new',result:null,override:null};}

const FIELD_MAP={age:['age'],weightLoss:['weightCurrent','weightPrevious'],pregnancy:['pregnancy'],unhealthyHabits:['unhealthyHabits'],communicationBarriers:['communicationBarriers'],psychiatricHistory:['psychiatricHistory'],psychologicalDistress:['distressMethod','hadsTotal','hadsAnxiety','hadsDepression','distressEva'],pfeiffer:['pfeifferErrors','literate'],ecog:['ecog'],socialSupport:['socialSupport'],comorbidities:['chronicDiseases'],doseAdjustment:['doseAdjustment'],pain:['painEva','poorPainControl'],acuteCare:['acuteCare'],dysphagia:['dysphagia'],treatmentSituation:['treatmentSituation'],polypharmacy:['homeMedicines'],routeChange:['routeChange'],regimenModification:['regimenModification'],highRiskMedication:['highRiskMedication'],specialStorage:['specialStorage'],complexRegimen:['complexRegimen'],interactions:['interactionCam','interactionPk','interactionC','interactionDX'],toxicity:['toxicityGrade'],adherence:['dispensingPercent','moriskyIncorrect'],specialTreatment:['clinicalTrial','specialUse','recentlyMarketed']};
const valuesFor=(id,value)=>{switch(id){case'weightLoss':return {weightCurrent:value?.currentWeight,weightPrevious:value?.previousWeight};case'psychologicalDistress':return {distressMethod:value?.method,hadsTotal:value?.total,hadsAnxiety:value?.anxiety,hadsDepression:value?.depression,distressEva:value?.eva};case'pfeiffer':return {pfeifferErrors:value?.errors,literate:value?.literate};case'pain':return {painEva:value?.eva,poorPainControl:value?.poorControl};case'treatmentSituation':return {treatmentSituation:value?.situation};case'interactions':return {interactionCam:false,interactionPk:false,interactionC:value==='C',interactionDX:['D','X'].includes(value)};case'adherence':return value||{};case'specialTreatment':return value||{};default:return {[FIELD_MAP[id]?.[0]]:value};}};
export function mergeExtraction(state,extraction,{preserveManual=true}={}){const next={...state,answers:{...state.answers},extraction:{...extraction.results},manualFields:[...(state.manualFields||[])]};for(const [id,trace] of Object.entries(extraction.results)){if(trace.confidenceStatus==='not_found')continue;for(const [field,value] of Object.entries(valuesFor(id,trace.proposedValue))){if(value===null||value===undefined)continue;if(preserveManual&&next.manualFields.includes(field))continue;next.answers[field]=value;}}return next;}
export function markManual(state,field,value){const id=Object.keys(FIELD_MAP).find(key=>FIELD_MAP[key].includes(field));const extraction={...(state.extraction||{})};if(id)extraction[id]={...(extraction[id]||{variableId:id,proposedValue:value,evidence:'',reason:'Introducido por el profesional.',source:'manual',method:'manual',extractedAt:new Date().toISOString()}),confidenceStatus:'manual',reviewed:true};return {...state,answers:{...state.answers,[field]:value},manualFields:[...new Set([...(state.manualFields||[]),field])],extraction};}
export function confirmVariable(state,id){const trace=state.extraction?.[id];return trace?{...state,extraction:{...state.extraction,[id]:{...trace,reviewed:true}}}:state;}
export function unresolvedExtraction(state){return Object.values(state.extraction||{}).filter(t=>t.confidenceStatus==='suggested'&&!t.reviewed||CRITICAL_VARIABLES.has(t.variableId)&&t.confidenceStatus==='confirmed'&&!t.reviewed);}
export function effectiveAnswers(state){const blocked=new Set(unresolvedExtraction(state).flatMap(t=>FIELD_MAP[t.variableId]||[]));return Object.fromEntries(Object.entries(state.answers||{}).filter(([k])=>!blocked.has(k)));}
export function canFinalize(state){const extractionPending=unresolvedExtraction(state);const clinicalPending=[...new Set(VARIABLES.flatMap(v=>v.required).filter(k=>state.answers?.[k]===undefined||state.answers[k]===null||state.answers[k]===''))];return {ok:!extractionPending.length&&!clinicalPending.length,extractionPending,clinicalPending};}
