const RESULT = (status='not_found', value=null, evidence='', reason='No se encontró información explícita.') => ({status,value,evidence,reason});
const sentence = (text,index) => {
  const start=Math.max(text.lastIndexOf('.',index)+1,text.lastIndexOf('\n',index)+1,0);
  const ends=[text.indexOf('.',index),text.indexOf('\n',index)].filter(x=>x>=0);
  return text.slice(start,ends.length?Math.min(...ends)+1:Math.min(text.length,index+180)).trim().slice(0,240);
};
const matchResult=(text,re,value,status='confirmed',reason='Mención clínica explícita.')=>{const m=re.exec(text);return m?RESULT(status,value(m),sentence(text,m.index),reason):RESULT();};
const uncertainNegation=(text,term)=>new RegExp(`(?:no\\s+(?:consta|se\\s+documenta|hay\\s+datos)|sin\\s+datos)(?:[^.\\n]{0,35})${term}`,'i').test(text);
const explicitNegative=(text,term)=>new RegExp(`(?:no\\s+(?:presenta|tiene|refiere)|sin|niega)(?:[^.\\n]{0,25})${term}`,'i').exec(text);

export function extractAge(text){return matchResult(text,/(?:paciente\s+de\s+|edad\s*[:=]?\s*|\b)(\d{1,3})\s*años\b/i,m=>Number(m[1]));}
export function extractPregnancy(text){const historical=/(?:antecedente|historia|previo|hace\s+\w+)[^.\n]{0,35}(?:embarazo|gestante)/i;if(historical.test(text))return RESULT('not_found',null,sentence(text,historical.exec(text).index),'Referencia histórica, no embarazo actual.');return matchResult(text,/\b(?:embarazada|gestante|embarazo\s+de\s+\d+\s+semanas)\b/i,()=>true);}
export function extractWeightLoss(text){const current=/(?:peso\s+actual|actualmente\s+pesa)\s*[:=]?\s*(\d+(?:[.,]\d+)?)\s*kg/i.exec(text);const previous=/(?:peso\s+(?:hace|de\s+hace)\s*(?:3|tres)\s+meses|hace\s+(?:3|tres)\s+meses\s+(?:pesaba|peso))\s*[:=]?\s*(\d+(?:[.,]\d+)?)\s*kg/i.exec(text);if(!current&&!previous)return RESULT();const evidence=sentence(text,(current||previous).index);return RESULT(current&&previous?'confirmed':'suggested',{currentWeight:current?Number(current[1].replace(',','.')):null,previousWeight:previous?Number(previous[1].replace(',','.')):null},evidence,current&&previous?'Pesos actual y de hace tres meses explícitos.':'Solo se encontró uno de los pesos requeridos.');}
export function extractPsychiatricHistory(text){if(uncertainNegation(text,'antecedentes?\\s+psiquiátric'))return RESULT('not_found',null,sentence(text,text.search(/no\s+consta/i)),'“No consta” expresa ausencia de documentación, no una respuesta negativa.');const n=explicitNegative(text,'antecedentes?\\s+psiquiátric');if(n)return RESULT('confirmed',false,sentence(text,n.index),'Negación clínica explícita.');return matchResult(text,/(?:antecedentes?\s+psiquiátricos?|depresión|trastorno\s+(?:de\s+)?ansiedad)/i,()=>true);}
export function extractHADS(text){const total=/HADS(?:\s+total)?\s*[:=]?\s*(\d{1,2})/i.exec(text), anxiety=/(?:HADS[- ]?A|ansiedad)\s*[:=]?\s*(\d{1,2})/i.exec(text), depression=/(?:HADS[- ]?D|depresión)\s*[:=]?\s*(\d{1,2})/i.exec(text);if(!total&&!anxiety&&!depression)return RESULT();return RESULT('confirmed',{total:total&&Number(total[1]),anxiety:anxiety&&Number(anxiety[1]),depression:depression&&Number(depression[1])},sentence(text,(total||anxiety||depression).index),'Puntuación HADS explícita.');}
export function extractDistress(text){return matchResult(text,/(?:EVA\s+(?:de\s+)?distress|termómetro\s+(?:de\s+)?distr[eé]s|distress)\s*[:=]?\s*(\d{1,2})/i,m=>Number(m[1]));}
export function extractPfeiffer(text){const m=/(?:Pfeiffer|SPMSQ)[^\d.\n]{0,25}(\d{1,2})\s*(?:errores?)?/i.exec(text);if(!m)return RESULT();const literacy=/(?:sabe\s+leer\s+y\s+escribir|alfabetizad[oa])/i.test(text)?true:/(?:analfabet[oa]|no\s+sabe\s+leer)/i.test(text)?false:null;return RESULT(literacy===null?'suggested':'confirmed',{errors:Number(m[1]),literate:literacy},sentence(text,m.index),literacy===null?'Falta el dato de alfabetización necesario para interpretar la escala.':'Pfeiffer y alfabetización explícitos.');}
export function extractECOG(text){return matchResult(text,/(?:PS\s*)?ECOG\s*[:=]?\s*([0-4])|performance\s+status\s*[:=]?\s*([0-4])/i,m=>Number(m[1]??m[2]));}
export function extractAdmissions(text){const old=/(?:ingreso|hospitalizaci[oó]n|urgencias)[^.\n]{0,45}(?:en\s+(?:19|20)\d{2}|hace\s+(?:\d+|un[oa]|dos|tres|cuatro|cinco)\s+años?)/i.exec(text);if(old)return RESULT('not_found',null,sentence(text,old.index),'Evento fuera del último mes.');const recent=/(?:ingreso|hospitalizaci[oó]n|urgencias)[^.\n]{0,55}(?:hace\s+(?:[1-4]|una|dos|tres|cuatro)\s+semanas?|en\s+el\s+[uú]ltimo\s+mes)|(?:hace\s+(?:[1-4]|una|dos|tres|cuatro)\s+semanas?)[^.\n]{0,55}(?:ingreso|hospitalizaci[oó]n|urgencias)/i.exec(text);if(recent)return RESULT('confirmed',true,sentence(text,recent.index),'Evento explícito dentro del último mes.');const any=/(?:ingreso|hospitalizaci[oó]n|urgencias)/i.exec(text);return any?RESULT('suggested',true,sentence(text,any.index),'Se menciona el evento, pero no su temporalidad.'):RESULT();}
export function extractDysphagia(text){if(uncertainNegation(text,'disfagia|dificultad\s+(?:para\s+)?(?:tragar|deglutir)'))return RESULT();const n=explicitNegative(text,'disfagia|dificultad\s+(?:para\s+)?(?:tragar|deglutir)');if(n)return RESULT('confirmed',false,sentence(text,n.index),'Negación clínica explícita.');const possible=/(?:posible|probable|sospecha\s+de)\s+disfagia/i.exec(text);if(possible)return RESULT('suggested',true,sentence(text,possible.index),'Expresión de posibilidad, requiere confirmación.');return matchResult(text,/\b(?:presenta\s+)?disfagia\b|dificultad\s+(?:para\s+)?(?:tragar|deglutir)/i,()=>true);}
export function extractTreatmentLine(text){const m=/(?:\b(1|2|3|4|5)\s*[ªa]\s*línea|\b(1|2|3|4|5)L\b|\b(primera|segunda|tercera|cuarta|quinta)\s+línea)/i.exec(text);if(!m)return RESULT();const words={primera:1,segunda:2,tercera:3,cuarta:4,quinta:5},line=Number(m[1]||m[2])||words[m[3].toLowerCase()];return RESULT('confirmed',{line,situation:line>=3?'thirdOrLater':line===1?'firstOrChange':'neither'},sentence(text,m.index),'Línea de tratamiento explícita.');}
export function extractPolypharmacy(text){const m=/(?:medicaci[oó]n\s+(?:domiciliaria|concomitante)|toma)\s*[:=]?\s*(\d{1,2})\s+medicamentos?/i.exec(text);return m?RESULT('confirmed',Number(m[1]),sentence(text,m.index),'Número explícito de medicamentos concomitantes.'):RESULT();}
export function extractDoseModification(text){const old=/(?:ajuste|reducci[oó]n|retraso)\s+(?:de\s+)?dosis[^.\n]{0,40}(?:hace\s+(?:\d+|un[oa]|dos|tres|cuatro|cinco)\s+años?|en\s+(?:19|20)\d{2})/i.exec(text);if(old)return RESULT();const recent=/(?:ajuste|reducci[oó]n|retraso)\s+(?:de\s+)?dosis[^.\n]{0,45}(?:hace\s+\d+\s+(?:días?|semanas?|mes(?:es)?)|[uú]ltimos?\s+dos\s+meses)/i.exec(text);if(recent)return RESULT('confirmed',true,sentence(text,recent.index),'Modificación temporalmente compatible con los últimos dos meses.');const any=/(?:ajuste|reducci[oó]n|retraso)\s+(?:de\s+)?dosis/i.exec(text);return any?RESULT('suggested',true,sentence(text,any.index),'Temporalidad no explícita.'):RESULT();}
export function extractInteractions(text){const m=/(?:interacci[oó]n\s+farmacol[oó]gica|DDI)[^.\n]{0,55}(?:nivel|categoría)\s*([CDX])(?:[^.\n]{0,30}Lexicomp)?|Lexicomp[^.\n]{0,40}(?:nivel|categoría)\s*([CDX])/i.exec(text);return m?RESULT('confirmed',(m[1]||m[2]).toUpperCase(),sentence(text,m.index),'Valoración profesional explícita de interacción.'):RESULT();}
export function extractToxicity(text){const historical=/(?:antecedente|previa?)[^.\n]{0,45}toxicidad[^.\n]{0,45}(?:hace\s+(?:\d+|un[oa]|dos|tres|cuatro|cinco)\s+años?|ya\s+resuelta)/i.exec(text);if(historical)return RESULT('not_found',null,sentence(text,historical.index),'Toxicidad histórica o resuelta, no actual.');const recent=/(?:toxicidad[^.\n]{0,25}(?:grado\s*)?([0-5])|CTCAE\s*(?:grado\s*)?([0-5])|\bG([0-5])\b)[^.\n]{0,55}(?:ciclo\s+(?:anterior|actual)|[uú]ltimos?\s+(?:tres|3)\s+ciclos)/i.exec(text);if(recent)return RESULT('confirmed',Number(recent[1]??recent[2]??recent[3]),sentence(text,recent.index),'Toxicidad con temporalidad compatible.');const any=/(?:toxicidad[^.\n]{0,25}(?:grado\s*)?([0-5])|CTCAE\s*(?:grado\s*)?([0-5]))/i.exec(text);return any?RESULT('suggested',Number(any[1]??any[2]),sentence(text,any.index),'Grado explícito, temporalidad no confirmada.'):RESULT();}
export function extractAdherence(text){const dispensing=/(?:dispensaci[oó]n|adherencia)\s*[:=]?\s*(\d{1,3}(?:[.,]\d+)?)\s*%/i.exec(text);const non=/Morisky\s*[:=]?\s*no\s+adherente/i.exec(text), yes=/Morisky\s*[:=]?\s*adherente/i.exec(text);if(!dispensing&&!non&&!yes)return RESULT();return RESULT(dispensing&&(non||yes)?'confirmed':'suggested',{dispensingPercent:dispensing?Number(dispensing[1].replace(',','.')):null,moriskyIncorrect:non?true:yes?false:null},sentence(text,(dispensing||non||yes).index),'Componentes de adherencia extraídos sin calcular la regla clínica.');}
export function extractSimpleExplicit(text,positive,negative){if(uncertainNegation(text,positive))return RESULT();const n=explicitNegative(text,negative||positive);if(n)return RESULT('confirmed',false,sentence(text,n.index),'Negación clínica explícita.');return matchResult(text,new RegExp(positive,'i'),()=>true);}

export const EXTRACTORS={
 age:extractAge,weightLoss:extractWeightLoss,pregnancy:extractPregnancy,
 unhealthyHabits:t=>extractSimpleExplicit(t,'(?:consumo\\s+(?:de\\s+)?(?:alcohol|drogas)|alcoholismo|toxicomanía)','(?:consumo\\s+(?:de\\s+)?(?:alcohol|drogas)|alcohol|drogas)'),
 communicationBarriers:t=>extractSimpleExplicit(t,'(?:barrera\\s+(?:cultural|de\\s+comunicaci[oó]n)|dificultad\\s+idiomática)'),psychiatricHistory:extractPsychiatricHistory,
 psychologicalDistress:t=>{const h=extractHADS(t),d=extractDistress(t);return h.status!=='not_found'?RESULT(h.status,{method:'hads',...h.value},h.evidence,h.reason):d.status!=='not_found'?RESULT(d.status,{method:'eva',eva:d.value},d.evidence,d.reason):RESULT();},
 pfeiffer:extractPfeiffer,ecog:extractECOG,
 socialSupport:t=>matchResult(t,/(?:situaci[oó]n\s+socioecon[oó]mica|falta\s+de\s+apoyo\s+social)[^.\n]{0,70}(?:impide|dificulta|imposibilita)[^.\n]{0,50}(?:tratamiento|adherencia)/i,()=>true,'suggested','Impacto social detectado; requiere confirmación profesional.'),
 comorbidities:t=>matchResult(t,/(?:comorbilidades|enfermedades\s+cr[oó]nicas)\s*[:=]?\s*(\d{1,2})/i,m=>Number(m[1])),
 doseAdjustment:t=>matchResult(t,/(?:insuficiencia|alteraci[oó]n)\s+(?:renal|hep[aá]tica)|FEVI\s+(?:reducida|baja)/i,()=>true,'suggested','Posible repercusión en dosis; requiere valoración profesional.'),
 pain:t=>{const m=/(?:EVA\s+(?:de\s+)?dolor|dolor\s+EVA)\s*[:=]?\s*(\d{1,2})/i.exec(t);return m?RESULT('suggested',{eva:Number(m[1]),poorControl:null},sentence(t,m.index),'La EVA no determina por sí sola mal control.'):RESULT();},
 acuteCare:extractAdmissions,dysphagia:extractDysphagia,treatmentSituation:extractTreatmentLine,polypharmacy:extractPolypharmacy,
 routeChange:t=>matchResult(t,/(?:cambio\s+de\s+(?:vía|forma\s+farmac[eé]utica)|cambio\s+a\s+(?:gen[eé]rico|biosimilar))/i,()=>true,'suggested','Cambio descrito; requiere validación profesional.'),
 regimenModification:extractDoseModification,
 highRiskMedication:t=>matchResult(t,/(?:medicamento|medicaci[oó]n)\s+de\s+alto\s+riesgo/i,()=>true,'suggested','La clasificación de alto riesgo debe confirmarse.'),
 specialStorage:t=>matchResult(t,/(?:conservaci[oó]n|almacenamiento)\s+(?:especial|entre\s+\d+\s*y\s+\d+\s*º?C|refrigerad[oa])/i,()=>true,'suggested','Condición de conservación mencionada.'),
 complexRegimen:t=>matchResult(t,/(?:pauta|r[eé]gimen)\s+(?:oral\s+)?discontinu[oa]/i,()=> 'one','suggested','La mención no permite asumir automáticamente toda la complejidad.'),
 interactions:extractInteractions,toxicity:extractToxicity,adherence:extractAdherence,
 specialTreatment:t=>{const trial=/ensayo\s+clínico/i.exec(t),special=/(?:uso|medicaci[oó]n)\s+especial/i.exec(t),recent=/(?:recientemente\s+comercializado|nuevo\s+medicamento)/i.exec(t);if(!trial&&!special&&!recent)return RESULT();return RESULT('suggested',{clinicalTrial:!!trial,specialUse:!!special,recentlyMarketed:!!recent},sentence(t,(trial||special||recent).index),'Condición especial mencionada; requiere confirmación.');}
};

export function extractClinicalText(text,now=new Date()){
 const normalized=String(text||'').normalize('NFC');
 const extractedAt=now.toISOString();
 const results=Object.fromEntries(Object.entries(EXTRACTORS).map(([variableId,fn])=>{const r=fn(normalized);return [variableId,{variableId,proposedValue:r.value,confidenceStatus:r.status,evidence:r.evidence,reason:r.reason,source:'clinical_text',method:`deterministic:${fn.name||variableId}`,extractedAt}];}));
 const summary=Object.values(results).reduce((s,r)=>(s[r.confidenceStatus]++,s),{confirmed:0,suggested:0,not_found:0});
 return {results,summary,extractedAt};
}
